"use client";

import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useStore } from '../store/useStore';
import { 
  Coins, 
  GitFork, 
  Cpu, 
  Binary, 
  Eye, 
  Play 
} from 'lucide-react';

const TABS = [
  { id: 'Tokens', label: 'Tokens', icon: Coins, desc: 'Lexical analysis token stream and span mappings.' },
  { id: 'AST', label: 'AST', icon: GitFork, desc: 'Abstract Syntax Tree nodes generated by the parser.' },
  { id: 'HIR', label: 'HIR', icon: Eye, desc: 'High-level Intermediate Representation after semantic checks.' },
  { id: 'Cranelift IR', label: 'Cranelift IR', icon: Cpu, desc: 'Cranelift intermediate representation (CLIF) for codegen.' },
  { id: 'Disassembly', label: 'Disassembly', icon: Binary, desc: 'Native machine code assembly disassembly.' },
  { id: 'Execution', label: 'Execution', icon: Play, desc: 'VM bytecode execution controls and stepping history.' },
];

export default function PanelTabs() {
  const { selectedPanel, setSelectedPanel } = useStore();

  const activeTab = TABS.find(t => t.id === selectedPanel) || TABS[0];
  const Icon = activeTab.icon;

  return (
    <div className="flex flex-col h-full w-full">
      {/* Tab bar */}
      <div className="flex border-b border-zinc-800 bg-zinc-900/20 px-2 pt-2 gap-1 overflow-x-auto scrollbar-none flex-shrink-0">
        {TABS.map((tab) => {
          const TabIcon = tab.icon;
          const isActive = selectedPanel === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setSelectedPanel(tab.id)}
              className={`relative flex items-center gap-2 px-4 py-2.5 rounded-t-lg text-xs font-medium transition-colors hover:text-zinc-200 z-10 ${
                isActive ? 'text-indigo-400 border-b-2 border-indigo-500 bg-zinc-900/50' : 'text-zinc-500'
              }`}
            >
              <TabIcon className="h-3.5 w-3.5" />
              {tab.label}
              {isActive && (
                <motion.div
                  layoutId="activeTabUnderline"
                  className="absolute bottom-0 inset-x-0 h-[2px] bg-indigo-500"
                  transition={{ type: 'spring', stiffness: 380, damping: 30 }}
                />
              )}
            </button>
          );
        })}
      </div>

      {/* Panel Content (with AnimatePresence transitions) */}
      <div className="flex-1 min-h-0 bg-zinc-900/10 p-6 flex items-center justify-center relative overflow-hidden">
        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab.id}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            transition={{ duration: 0.15 }}
            className="flex flex-col items-center justify-center max-w-sm text-center p-8 border border-zinc-800/40 rounded-2xl bg-zinc-900/30 backdrop-blur-sm shadow-xl"
          >
            <div className="p-4 rounded-full bg-zinc-900 border border-zinc-850 text-indigo-400 mb-4 shadow-inner">
              <Icon className="h-8 w-8" />
            </div>
            <h3 className="text-sm font-semibold text-zinc-200 mb-1">{activeTab.label}</h3>
            <p className="text-xs text-zinc-500 leading-relaxed">{activeTab.desc}</p>
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
}
