"use client";

import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useStore } from '../store/useStore';
import TreeView from './TreeView';
import ClifPanel from './ClifPanel';
import DisassemblyPanel from './DisassemblyPanel';
import ExecutionPanel from './ExecutionPanel';
import { parseAstOrHirToTree } from '../utils/treeParser';
import { 
  Coins, 
  GitFork, 
  Cpu, 
  Binary, 
  Eye, 
  Play,
  FileCode2
} from 'lucide-react';

const TABS = [
  { id: 'Tokens', label: 'Tokens', icon: Coins, desc: 'Lexical analysis token stream and span mappings.' },
  { id: 'AST', label: 'AST', icon: GitFork, desc: 'Abstract Syntax Tree nodes generated by the parser.' },
  { id: 'HIR', label: 'HIR', icon: Eye, desc: 'High-level Intermediate Representation after semantic checks.' },
  { id: 'Cranelift IR', label: 'Cranelift IR', icon: Cpu, desc: 'Cranelift intermediate representation (CLIF) for codegen.' },
  { id: 'Disassembly', label: 'Disassembly', icon: Binary, desc: 'Native machine code assembly disassembly.' },
  { id: 'Execution', label: 'Execution', icon: Play, desc: 'VM bytecode execution controls and stepping history.' },
];

export default function PanelTabs() {
  const { selectedPanel, setSelectedPanel, compileResult } = useStore();

  const activeTab = TABS.find(t => t.id === selectedPanel) || TABS[0];
  const Icon = activeTab.icon;

  const isTokensTab = selectedPanel === 'Tokens';
  const isAstTab = selectedPanel === 'AST';
  const isHirTab = selectedPanel === 'HIR';
  const isClifTab = selectedPanel === 'Cranelift IR';
  const isDisassemblyTab = selectedPanel === 'Disassembly';
  const isExecutionTab = selectedPanel === 'Execution';
  const tokenSnapshots = compileResult?.tokens ?? [];

  const hasContent = compileResult && (
    (isTokensTab && tokenSnapshots.length > 0) ||
    (isAstTab && compileResult.ast.length > 0) || 
    (isHirTab && compileResult.hir.length > 0) ||
    (isClifTab && compileResult.clif && compileResult.clif.length > 0) ||
    isDisassemblyTab ||
    isExecutionTab
  );

  // Parse trees if we have results
  const trees = React.useMemo(() => {
    if (!compileResult) return [];
    if (isAstTab) {
      return compileResult.ast.map((snap) =>
        parseAstOrHirToTree(snap.text, snap.start, snap.end, false)
      );
    }
    if (isHirTab) {
      return compileResult.hir.map((snap) =>
        parseAstOrHirToTree(snap.text, snap.start, snap.end, true)
      );
    }
    return [];
  }, [compileResult, isAstTab, isHirTab]);

  return (
    <div className="flex flex-col h-full w-full">
      {/* Tab bar */}
      <div className="flex border-b border-zinc-800 bg-zinc-900/20 px-2 pt-2 gap-1 overflow-x-auto scrollbar-none flex-shrink-0">
        {TABS.map((tab) => {
          const TabIcon = tab.icon;
          const isActive = selectedPanel === tab.id;
          
          let activeStyles = 'text-indigo-400 bg-zinc-900/50';
          let underlineBg = 'bg-indigo-500';
          
          if (tab.id === 'AST') {
            activeStyles = 'text-emerald-400 bg-zinc-900/50';
            underlineBg = 'bg-emerald-500';
          } else if (tab.id === 'HIR') {
            activeStyles = 'text-indigo-400 bg-zinc-900/50';
            underlineBg = 'bg-indigo-500';
          } else if (tab.id === 'Cranelift IR') {
            activeStyles = 'text-indigo-400 bg-zinc-900/50';
            underlineBg = 'bg-indigo-500';
          }

          return (
            <button
              key={tab.id}
              onClick={() => setSelectedPanel(tab.id)}
              className={`relative flex items-center gap-2 px-4 py-2.5 rounded-t-lg text-xs font-medium transition-colors hover:text-zinc-200 z-10 ${
                isActive ? activeStyles : 'text-zinc-500'
              }`}
            >
              <TabIcon className="h-3.5 w-3.5" />
              {tab.label}
              {isActive && (
                <motion.div
                  layoutId="activeTabUnderline"
                  className={`absolute bottom-0 inset-x-0 h-[2px] ${underlineBg}`}
                  transition={{ type: 'spring', stiffness: 380, damping: 30 }}
                />
              )}
            </button>
          );
        })}
      </div>

      {/* Panel Content */}
      <div className="flex-1 min-h-0 bg-zinc-900/10 flex flex-col relative overflow-hidden">
        <AnimatePresence mode="wait">
          {hasContent ? (
            isClifTab ? (
              <motion.div
                key="clif-content"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.15 }}
                className="flex-1 min-h-0"
              >
                <ClifPanel />
              </motion.div>
            ) : isDisassemblyTab ? (
              <motion.div
                key="disassembly-content"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.15 }}
                className="flex-1 min-h-0"
              >
                <DisassemblyPanel />
              </motion.div>
            ) : isExecutionTab ? (
              <motion.div
                key="execution-content"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.15 }}
                className="flex-1 min-h-0"
              >
                <ExecutionPanel />
              </motion.div>
            ) : isTokensTab ? (
              <motion.div
                key="tokens-content"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.15 }}
                className="flex-1 overflow-y-auto p-4 space-y-3"
              >
                {tokenSnapshots.map((token, idx) => (
                  <div
                    key={`${token.start}-${token.end}-${idx}`}
                    className="flex items-start gap-3 rounded-xl border border-indigo-500/10 bg-zinc-950/40 px-4 py-3 shadow-lg shadow-indigo-500/5"
                  >
                    <div className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-indigo-500/10 text-[11px] font-semibold text-indigo-300">
                      {idx + 1}
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2 text-[11px] font-medium uppercase tracking-[0.18em] text-zinc-500">
                        <span>{token.start}</span>
                        <span>→</span>
                        <span>{token.end}</span>
                      </div>
                      <div className="mt-1 font-mono text-sm text-zinc-200 whitespace-pre-wrap break-words">
                        {token.text}
                      </div>
                    </div>
                  </div>
                ))}
              </motion.div>
            ) : (
              <motion.div
                key={`${selectedPanel}-tree-content`}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.15 }}
                className="flex-1 overflow-y-auto p-4 space-y-4"
              >
                {trees.map((tree, idx) => (
                  <div 
                    key={tree.id || idx}
                    className={`p-4 border rounded-xl bg-zinc-950/40 backdrop-blur-md shadow-lg ${
                      isAstTab 
                        ? 'border-emerald-500/10 shadow-emerald-500/2'
                        : 'border-indigo-500/10 shadow-indigo-500/2'
                    }`}
                  >
                    <TreeView 
                      node={tree} 
                      colorClass={isAstTab ? 'emerald' : 'indigo'} 
                    />
                  </div>
                ))}
              </motion.div>
            )
          ) : (
            <motion.div
              key={`${activeTab.id}-placeholder`}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.15 }}
              className="flex-1 flex items-center justify-center p-6"
            >
              <div className="flex flex-col items-center justify-center max-w-sm text-center p-8 border border-zinc-800/40 rounded-2xl bg-zinc-900/30 backdrop-blur-sm shadow-xl">
                <div className={`p-4 rounded-full bg-zinc-900 border border-zinc-850 mb-4 shadow-inner ${
                  selectedPanel === 'AST' ? 'text-emerald-400' : 'text-indigo-400'
                }`}>
                  {compileResult && (isTokensTab || isAstTab || isHirTab || isClifTab) ? (
                    <FileCode2 className="h-8 w-8" />
                  ) : (
                    <Icon className="h-8 w-8" />
                  )}
                </div>
                <h3 className="text-sm font-semibold text-zinc-200 mb-1">
                  {compileResult && (isTokensTab || isAstTab || isHirTab || isClifTab) ? 'Empty Output' : activeTab.label}
                </h3>
                <p className="text-xs text-zinc-500 leading-relaxed">
                  {compileResult && (isTokensTab || isAstTab || isHirTab || isClifTab) 
                    ? 'No output generated in compilation.'
                    : activeTab.desc}
                </p>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
